# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productdetail', to='case.Product', verbose_name='Товар')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('productattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='case.ProductAttribute')),
            ],
            bases=('case.productattribute',),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('productattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='case.ProductAttribute')),
            ],
            bases=('case.productattribute',),
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('productattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='case.ProductAttribute')),
            ],
            bases=('case.productattribute',),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colordetail', to='case.Color', verbose_name='Цвет товара'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materialdetail', to='case.Material', verbose_name='Материал товара'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizedetail', to='case.Size', verbose_name='Размер товара'),
        ),
    ]
